// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmfavwzuipzcuywjotih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtZmF2d3p1aXB6Y3V5d2pvdGloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MjA2MjAsImV4cCI6MjA2NjA5NjYyMH0.q5lbM77k-l1oUYEGizSes6OdVT1lq8l1R0pvK93zfu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);